# -*- cmake -*-
include(Prebuilt)

if( TARGET expat::expat )
    return()
endif()
create_target( expat::expat INTERFACE IMPORTED )

use_prebuilt_binary(expat)
if (WINDOWS)
    set_target_libraries( expat::expat libexpatMT )
    set(EXPAT_COPY libexpatMT.dll)
else (WINDOWS)
    set_target_libraries( expat::expat expat )
    if (DARWIN)
        set(EXPAT_COPY libexpat.1.dylib libexpat.dylib)
    else ()
        set(EXPAT_COPY libexpat.so.1 libexpat.so)
    endif ()
endif (WINDOWS)
set_target_include_dirs( expat::expat ${LIBS_PREBUILT_DIR}/include )
