# -*- cmake -*-
include_guard()
add_library(ll::libvlc INTERFACE IMPORTED)

if(LIBVLCPLUGIN)
    find_library(LIBVLC_LIBRARY_RELEASE NAMES vlc PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
    find_library(LIBVLCCORE_LIBRARY_RELEASE NAMES vlccore PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
    target_link_libraries(ll::libvlc INTERFACE ${LIBVLC_LIBRARY_RELEASE} ${LIBVLCCORE_LIBRARY_RELEASE})
    target_include_directories(ll::libvlc SYSTEM INTERFACE ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include)
endif()
