include(Prebuilt)

if( TARGET nghttp2::nghttp2 )
  return()
endif()
create_target( nghttp2::nghttp2 )

use_prebuilt_binary(nghttp2)
if (WINDOWS)
  set_target_libraries( nghttp2::nghttp2 ${ARCH_PREBUILT_DIRS_RELEASE}/nghttp2.lib)
elseif (DARWIN)
  set_target_libraries( nghttp2::nghttp2 libnghttp2.dylib)
else (WINDOWS)
  set_target_libraries( nghttp2::nghttp2 libnghttp2.a )
endif (WINDOWS)
set_target_include_dirs( nghttp2::nghttp2 ${LIBS_PREBUILT_DIR}/include/nghttp2)
