/** 
 * @file llstatenums.h
 *
 * Copyright (c) 2001-$CurrentYear$, Linden Research, Inc.
 * $License$
 */

#ifndef LL_LLSTATENUMS_H
#define LL_LLSTATENUMS_H

enum
{
	LL_SIM_STAT_TIME_DILATION,
	LL_SIM_STAT_FPS,
	LL_SIM_STAT_PHYSFPS,
	LL_SIM_STAT_AGENTUPS,
	LL_SIM_STAT_FRAMEMS,
	LL_SIM_STAT_NETMS,
	LL_SIM_STAT_SIMOTHERMS,
	LL_SIM_STAT_SIMPHYSICSMS,
	LL_SIM_STAT_AGENTMS,
	LL_SIM_STAT_IMAGESMS,
	LL_SIM_STAT_SCRIPTMS,
	LL_SIM_STAT_NUMTASKS,
	LL_SIM_STAT_NUMTASKSACTIVE,
	LL_SIM_STAT_NUMAGENTMAIN,
	LL_SIM_STAT_NUMAGENTCHILD,
	LL_SIM_STAT_NUMSCRIPTSACTIVE,
	LL_SIM_STAT_LSLIPS,
	LL_SIM_STAT_INPPS,
	LL_SIM_STAT_OUTPPS,
	LL_SIM_STAT_PENDING_DOWNLOADS,
	LL_SIM_STAT_PENDING_UPLOADS,
	LL_SIM_STAT_VIRTUAL_SIZE_KB,
	LL_SIM_STAT_RESIDENT_SIZE_KB,
	LL_SIM_STAT_PENDING_LOCAL_UPLOADS,
	LL_SIM_STAT_TOTAL_UNACKED_BYTES
};

#endif
