name: New Viewer Application
description: Submit a request for your viewer to be added to the list of approved third party viewers.
title: "[TPV APPLICATION]: "
labels: ["tpv-application"]
body:
  - type: markdown
    attributes:
      value: |
        When filing an application to have your viewer added to the list of approved third party viewers, please follow the guidlines in this form
        as well as the [Third Party Viewer Policy](https://secondlife.com/corporate/third-party-viewers).

        _Please note that this form is public and will be visible to anyone who visits this repository._
  - type: input
    id: viewer-name
    attributes:
      label: Viewer Name
      description: The name of the viewer you are submitting.
      placeholder: Viewer Name
    validations:
      required: true
  - type: input
    id: home-url
    attributes:
      label: Home URL
      description: The URL to the viewer's homepage.
      placeholder: https://example.com
  - type: input
    id: vcs-url 
    attributes:
      label: Version Control System URL
      description: The URL to the viewer's public version control system (GitHub, GitLab, etc.) containing the source code of your viewer.
      placeholder: https://github.com/secondlife/viewer
    validations:
      required: true
  - type: input
    id: download-url 
    attributes:
      label: Download URL
      description: The URL to download the viewer.
      placeholder: https://example.com/downloads
    validations:
      required: true
  - type: input
    id: contact-email
    attributes:
      label: Contact Email
      description: The email address for the viewer's support team.
      placeholder: myname at example dot org
    validations:
      required: true
  - type: input
    id: contact-sl
    attributes:
      label: Contact Second Life User
      description: Primary contact in Second Life. 
      placeholder: Second Life user
    validations:
      required: true
  - type: input
    id: contact-sl-group
    attributes:
      label: Contact Second Life Group
      description: Second Life group for support and announcements. 
      placeholder: Second Life group 
  - type: textarea 
    id: customer-support-info
    attributes:
      label: Customer Support Information
      description: Information about the viewer's customer support.
      placeholder: https://example.com/support
    validations:
      required: true
  - type: textarea 
    id: features
    attributes:
      label: Featureset 
      description: |
        Any surprising or unexpected functionality, including
        limitations on features and functionality generally available to Second Life users. 
      placeholder: |
        * Feature 1
        * Feature 2
  - type: textarea
    id: short-description
    attributes:
      label: Short Description
      description: |
        A brief description of the viewer that will appear on the [Third Party Viewer Directory](https://wiki.secondlife.com/wiki/Third_Party_Viewer_Directory).
      placeholder: A brief description of the viewer.
    validations:
      required: true
  - type: textarea
    id: long-description
    attributes:
      label: Long Description
      description: |
        A more detailed description of the viewer that will appear on your viewer's wiki page. 
      placeholder: A more detailed description of the viewer.
    validations:
      required: true
  - type: input
    id: platfroms
    attributes:
      label: Platforms
      description: The platforms the viewer is available on.
      placeholder: Windows, macOS, Linux
    validations:
      required: true
  - type: input
    id: privacy-policy
    attributes:
      label: Privacy Policy
      description: The URL to the viewer's privacy policy.
      placeholder: https://example.com/privacy
    validations:
      required: true
  - type: textarea
    id: icon
    attributes:
      label: Icon
      description: |
        Attach a file or provide a URL to the viewer's icon. (At least 512x512)
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: https://example.com/icon.png
    validations:
      required: true
  - type: checkboxes
    id: policy-agreement 
    attributes:
      label: Third Party Viewer Policy Agreement 
      description: By submitting this issue, you agree that the information submitted is accurate and that you will follow the Third Party Viewer Policy. 
      options:
        - label: I agree 
          required: true
