blank_issues_enabled: false
contact_links:
- name: 💬 Community Feedback (Canny)
  url: https://feedback.secondlife.com
  about: Space for discussing and reviewing user-impacting bug reports and feature requests.
