#! /bin/bash

#
# The first argument contains the path to the installer app.  The second a path
# to a marker file which should be created if the installer fails.q
#

cd "$(dirname "$0")"
../Resources/mac-updater.app/Contents/MacOS/mac-updater -dmg "$1" -name "Second Life Viewer 2" -marker "$2" &
exit 0
