set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_C_FLAGS_RELEASE "")
set(VCPKG_CXX_FLAGS_RELEASE "/std:c++20 /Zc:__cplusplus")
