name: Stale PRs 
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        id: stale
        with:
          stale-pr-message: This pull request is stale because it has been open 30 days with no activity. Remove stale label or comment or it will be closed in 7 days
          days-before-stale: 30
          days-before-close: 7 
          exempt-pr-labels: blocked,must,should,keep
          stale-pr-label: stale
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
