#!/usr/bin/env bash

exe="$1"
if [[ "$OSTYPE" == darwin* && -d "$exe" && "$exe" == *.app ]]
then
    exe="$(ls "$exe/Contents/MacOS/Second Life "*)"
fi

"$exe" --autologin --luafile 'frame_profile_quit.lua 228 232 26' \
     http://maps.secondlife.com/secondlife/Bug%20Island/220/224/27
